name: py312_PRForm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - tqdm
  - h5py
  - mmseqs2
  - seaborn
  - matplotlib
  - scikit-learn
  - biopython
  - bcbio-gff
  - ete3
  - ncbi-datasets-cli
  - ipykernel
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - prokka